version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - checkout
      - run:
          name: Determine which directories have changed
          command: |
            echo "Determine which directories have changed"
  cloud-gateway:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run:
          name: cloud-gateway have changed
          command: |
            echo "cloud-gateway have changed"
  customers-service:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run:
          name: customers-service have changed
          command: |
            echo "customers-service have changed"
  vets-service:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run:
          name: vets-service have changed
          command: |
            echo "vets-service have changed"
  visits-service:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run:
          name: visits-service have changed
          command: |
            echo "visits-service have changed"
  web-app:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run:
          name: web-app have changed
          command: |
            echo "web-app have changed"

commands:
  build-service:
    description: "Build a service and push image to dockerhub"
    parameters:
      service-name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/spring-petclinic-msa

      - setup_remote_docker

      - run:
          name: Login to Dockerhub
          command: docker login -u zwp2107 -p zwp610315

      # Download and cache dependencies
      - restore_cache:
          keys:
            - << parameters.service-name >>-{{ checksum "pom.xml"}}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: << parameters.service-name >>-{{ checksum "pom.xml"}}

      # package into a jar and build image
      - run: mvn clean package -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI -Ddockerfile.maven.settings.auth=false

      # push docker image to docker hub
      - run: mvn dockerfile:push -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI

      # store raw content of src code
      - store_artifacts:
          path: target/classes
          destination: spring-petclinic-<< parameters.service-name >>
