version: 2.1

jobs:
  cloud-gateway:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run: echo "cloud-gateway"
  customers-service:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run: echo " customers-service"
  vets-service:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run: echo " vets-service"
  visits-service:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run: echo "visits-service"
  web-app:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - run: echo " web-app"
